### ISSUE TITLE
Only works when name not followed by a dot

### ISSUE THREAD

**Issue by rithvikvibhu** [buffrr/letsdane#2]
I've got letsdane working (it's great, thanks @buffrr!) and it normally works fine. But when the name has a trailing dot, it doesn't.

Not a major problem, was just curious why this happens. (https://google.com. redirects normally)

Without a trailing dot:
![image](https://user-images.githubusercontent.com/5113343/99392910-856b3080-2902-11eb-9090-174fefac447c.png)

With a trailing dot:
![image](https://user-images.githubusercontent.com/5113343/99392937-8e5c0200-2902-11eb-8b28-848968f8b387.png)

The log:
![image](https://user-images.githubusercontent.com/5113343/99393213-04f8ff80-2903-11eb-84fa-26c864cf8a6a.png)

**Comment by buffrr** [comment]
Thank you for reporting this issue. The Server Name Indication (SNI) must not include a trailing dot per [RFC 6066](https://tools.ietf.org/html/rfc6066) Section 3. This is unfortunately an issue with the current way handshake TLDs are being used. So when using HTTPS you should remove it.  

The behavior of the trailing dot in SNI varies  you can try for example `https://cloudflare.com.` or `https://buffrr.dev.` without using any proxy and they will either fail in some browsers or show that the certificate is invalid because the name in the certificate does not include a trailing dot.

The Go standard TLS library follows RFC6066 and does not allow a trailing dot in SNI so unfortunately it's not possible to allow the usage of this (non-standard) behavior via letsdane

**Comment by rithvikvibhu** [comment]
Ah, good to know. Thanks again :)
